@host = localhost:8080

POST http://{{host}}/
Content-Type: application/json

{
  "hostname": "subdomain.yourdomain.examle",
  "target": "https://example.com"
}

###

GET http://{{host}}/

###

DELETE http://{{host}}/
Content-Type: application/json

{
  "hostname": "subdomain.yourdomain.examle"
}